package com.example.minicrpc.databasedao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LUCKY_DOG.
 */
public class LuckyDog {

    private Long id;
    private String portraitPath;
    private String name;
    private Integer sex;
    private java.util.Date birthday;
    private String tel;
    private String note;

    public LuckyDog() {
    }

    public LuckyDog(Long id) {
        this.id = id;
    }

    public LuckyDog(Long id, String portraitPath, String name, Integer sex, java.util.Date birthday, String tel, String note) {
        this.id = id;
        this.portraitPath = portraitPath;
        this.name = name;
        this.sex = sex;
        this.birthday = birthday;
        this.tel = tel;
        this.note = note;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPortraitPath() {
        return portraitPath;
    }

    public void setPortraitPath(String portraitPath) {
        this.portraitPath = portraitPath;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getSex() {
        return sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public java.util.Date getBirthday() {
        return birthday;
    }

    public void setBirthday(java.util.Date birthday) {
        this.birthday = birthday;
    }

    public String getTel() {
        return tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

}
