package com.example.minicrpc.databasedao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.minicrpc.databasedao.SmsCategory;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table SMS_CATEGORY.
*/
public class SmsCategoryDao extends AbstractDao<SmsCategory, Long> {

    public static final String TABLENAME = "SMS_CATEGORY";

    /**
     * Properties of entity SmsCategory.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property CategoryId = new Property(0, long.class, "categoryId", true, "CATEGORY_ID");
        public final static Property CategoryName = new Property(1, String.class, "categoryName", false, "CATEGORY_NAME");
    };

    private DaoSession daoSession;


    public SmsCategoryDao(DaoConfig config) {
        super(config);
    }
    
    public SmsCategoryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'SMS_CATEGORY' (" + //
                "'CATEGORY_ID' INTEGER PRIMARY KEY NOT NULL ," + // 0: categoryId
                "'CATEGORY_NAME' varchar NOT NULL );"); // 1: categoryName
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SMS_CATEGORY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, SmsCategory entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getCategoryId());
        stmt.bindString(2, entity.getCategoryName());
    }

    @Override
    protected void attachEntity(SmsCategory entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public SmsCategory readEntity(Cursor cursor, int offset) {
        SmsCategory entity = new SmsCategory( //
            cursor.getLong(offset + 0), // categoryId
            cursor.getString(offset + 1) // categoryName
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, SmsCategory entity, int offset) {
        entity.setCategoryId(cursor.getLong(offset + 0));
        entity.setCategoryName(cursor.getString(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(SmsCategory entity, long rowId) {
        entity.setCategoryId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(SmsCategory entity) {
        if(entity != null) {
            return entity.getCategoryId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
