package com.example.minicrpc.databasedao;

import java.util.List;
import com.example.minicrpc.databasedao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SMS_CATEGORY.
 */
public class SmsCategory {

    private long categoryId;
    /** Not-null value. */
    private String categoryName;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient SmsCategoryDao myDao;

    private List<SmsSonCategory> smsSonCategoryList;
    private List<SmsContent> smsContentList;

    public SmsCategory() {
    }

    public SmsCategory(long categoryId) {
        this.categoryId = categoryId;
    }

    public SmsCategory(long categoryId, String categoryName) {
        this.categoryId = categoryId;
        this.categoryName = categoryName;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getSmsCategoryDao() : null;
    }

    public long getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(long categoryId) {
        this.categoryId = categoryId;
    }

    /** Not-null value. */
    public String getCategoryName() {
        return categoryName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<SmsSonCategory> getSmsSonCategoryList() {
        if (smsSonCategoryList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            SmsSonCategoryDao targetDao = daoSession.getSmsSonCategoryDao();
            List<SmsSonCategory> smsSonCategoryListNew = targetDao._querySmsCategory_SmsSonCategoryList(categoryId);
            synchronized (this) {
                if(smsSonCategoryList == null) {
                    smsSonCategoryList = smsSonCategoryListNew;
                }
            }
        }
        return smsSonCategoryList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetSmsSonCategoryList() {
        smsSonCategoryList = null;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<SmsContent> getSmsContentList() {
        if (smsContentList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            SmsContentDao targetDao = daoSession.getSmsContentDao();
            List<SmsContent> smsContentListNew = targetDao._querySmsCategory_SmsContentList(categoryId);
            synchronized (this) {
                if(smsContentList == null) {
                    smsContentList = smsContentListNew;
                }
            }
        }
        return smsContentList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetSmsContentList() {
        smsContentList = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
